export const Actions = {
  EMPLOYEE_LIST    : 'EMPLOYEE_LIST',
  EDIT_EMPLOYEE    : 'EDIT_EMPLOYEE',
  UPDATE_EMPLOYEE  : 'UPDATE_EMPLOYEE',
  SEARCH_EMPLOYEE  : 'SEARCH_EMPLOYEE',
  SORT_EMPLOYEE    : 'SORT_EMPLOYEE'
};
